"""Application layer public facade."""

from .commands import (
    AddParticipantToCampaignCommand,
    AddVoiceSampleCommand,
    CreateCampaignCommand,
    ExportRecapMarkdownCommand,
    ExportTranscriptMarkdownCommand,
    GenerateRecapCommand,
    GetJobStatusCommand,
    ManualSpeakerMappingCommand,
    ReviewSpeakerMappingsCommand,
    RunProcessingJobCommand,
    SubmitRecordingForProcessingCommand,
)
from .errors import ApplicationError, InvalidOperationError, NotFoundError
from .results import (
    AddParticipantToCampaignResult,
    AddVoiceSampleResult,
    CreateCampaignResult,
    ExportMarkdownResult,
    GenerateRecapResult,
    GetJobStatusResult,
    ReviewSpeakerMappingsResult,
    RunProcessingJobResult,
    SubmitRecordingForProcessingResult,
    TranscriptChunk,
)
from .use_cases import (
    AddParticipantToCampaign,
    AddVoiceSample,
    CreateCampaign,
    ExportRecapMarkdown,
    ExportTranscriptMarkdown,
    GenerateRecap,
    GetJobStatus,
    ReviewSpeakerMappings,
    RunProcessingJob,
    SubmitRecordingForProcessing,
)

__all__ = [
    "AddParticipantToCampaign",
    "AddParticipantToCampaignCommand",
    "AddParticipantToCampaignResult",
    "AddVoiceSample",
    "AddVoiceSampleCommand",
    "AddVoiceSampleResult",
    "ApplicationError",
    "CreateCampaign",
    "CreateCampaignCommand",
    "CreateCampaignResult",
    "ExportMarkdownResult",
    "ExportRecapMarkdown",
    "ExportRecapMarkdownCommand",
    "ExportTranscriptMarkdown",
    "ExportTranscriptMarkdownCommand",
    "GenerateRecap",
    "GenerateRecapCommand",
    "GenerateRecapResult",
    "GetJobStatus",
    "GetJobStatusCommand",
    "GetJobStatusResult",
    "InvalidOperationError",
    "ManualSpeakerMappingCommand",
    "NotFoundError",
    "ReviewSpeakerMappings",
    "ReviewSpeakerMappingsCommand",
    "ReviewSpeakerMappingsResult",
    "RunProcessingJob",
    "RunProcessingJobCommand",
    "RunProcessingJobResult",
    "SubmitRecordingForProcessing",
    "SubmitRecordingForProcessingCommand",
    "SubmitRecordingForProcessingResult",
    "TranscriptChunk",
]
