"""Construction of the application use-case facade."""

from notekeeper.application import (
    AddParticipantToCampaign,
    AddVoiceSample,
    CancelProcessingJob,
    ClearFailedJobsForCampaign,
    CreateCampaign,
    CreateProcessingJobForAudioTrack,
    DeleteAudioTrack,
    DeleteCampaign,
    DeleteParticipant,
    DeleteProcessingJob,
    DeleteVoiceSample,
    ExportRecapMarkdown,
    ExportTranscriptMarkdown,
    GenerateRecap,
    GetCampaign,
    GetJobStatus,
    GetRecapGuidances,
    InspectAudioMetadata,
    InspectLocalAudioFile,
    ListAudioTracks,
    ListCampaigns,
    ListJobsForCampaign,
    ListParticipants,
    ListVoiceSamples,
    PreviewRecapMarkdown,
    PreviewTranscriptMarkdown,
    QueueProcessingJob,
    RegisterAudioTrack,
    RestartProcessingJob,
    ReviewSpeakerMappings,
    SubmitRecordingForProcessing,
    SyncCampaignFolder,
    UpdateAudioTrack,
    UpdateCampaign,
    UpdateParticipant,
    UpdateRecapGuidances,
    UpdateVoiceSample,
)
from notekeeper.application.ports import (
    CurrentUserProvider,
    JobManager,
    ProgressTrackerFactory,
)
from notekeeper.application.use_cases.utils import (
    CampaignMutationPolicy,
    GuardedCampaignMutation,
)
from notekeeper.interfaces import Stage1UseCases

from .factory import InfrastructureBundle


def wire_stage1_use_cases(
    infrastructure: InfrastructureBundle,
    *,
    progress_tracker_factory: ProgressTrackerFactory,
    job_manager: JobManager,
    mutation_policy: CampaignMutationPolicy,
    current_user: CurrentUserProvider | None = None,
) -> Stage1UseCases:
    queue_processing_job = QueueProcessingJob(
        infrastructure.job_repository,
        job_manager,
        mutation_policy,
        infrastructure.clock,
    )
    restart_processing_job = RestartProcessingJob(
        infrastructure.campaign_repository,
        infrastructure.audio_track_repository,
        infrastructure.job_repository,
        infrastructure.clock,
        infrastructure.id_generator,
    )
    return Stage1UseCases(
        create_campaign=CreateCampaign(
            infrastructure.campaign_repository,
            infrastructure.id_generator,
            infrastructure.recap_guidances,
            infrastructure.artifact_storage,
            current_user,
        ),
        get_campaign=GetCampaign(infrastructure.campaign_repository),
        list_campaigns=ListCampaigns(infrastructure.campaign_repository),
        update_campaign=GuardedCampaignMutation(
            UpdateCampaign(infrastructure.campaign_repository),
            mutation_policy,
        ),
        delete_campaign=DeleteCampaign(
            infrastructure.campaign_repository,
            infrastructure.artifact_storage,
            mutation_policy,
        ),
        add_participant=GuardedCampaignMutation(
            AddParticipantToCampaign(
                infrastructure.campaign_repository,
                infrastructure.id_generator,
            ),
            mutation_policy,
        ),
        list_participants=ListParticipants(infrastructure.campaign_repository),
        update_participant=GuardedCampaignMutation(
            UpdateParticipant(infrastructure.campaign_repository),
            mutation_policy,
        ),
        delete_participant=GuardedCampaignMutation(
            DeleteParticipant(infrastructure.campaign_repository),
            mutation_policy,
        ),
        add_voice_sample=GuardedCampaignMutation(
            AddVoiceSample(
                infrastructure.campaign_repository,
                infrastructure.metadata_reader,
                infrastructure.source_metadata_reader,
                infrastructure.artifact_storage,
                infrastructure.id_generator,
            ),
            mutation_policy,
        ),
        list_voice_samples=ListVoiceSamples(infrastructure.campaign_repository),
        delete_voice_sample=GuardedCampaignMutation(
            DeleteVoiceSample(infrastructure.campaign_repository),
            mutation_policy,
        ),
        update_voice_sample=GuardedCampaignMutation(
            UpdateVoiceSample(
                infrastructure.campaign_repository,
                infrastructure.metadata_reader,
            ),
            mutation_policy,
        ),
        register_audio_track=GuardedCampaignMutation(
            RegisterAudioTrack(
                infrastructure.campaign_repository,
                infrastructure.metadata_reader,
                infrastructure.id_generator,
                audio_normalizer=infrastructure.audio_normalizer,
                artifact_storage=infrastructure.artifact_storage,
            ),
            mutation_policy,
        ),
        list_audio_tracks=ListAudioTracks(infrastructure.campaign_repository),
        update_audio_track=GuardedCampaignMutation(
            UpdateAudioTrack(
                infrastructure.campaign_repository,
                infrastructure.metadata_reader,
                audio_normalizer=infrastructure.audio_normalizer,
                artifact_storage=infrastructure.artifact_storage,
            ),
            mutation_policy,
        ),
        delete_audio_track=GuardedCampaignMutation(
            DeleteAudioTrack(
                infrastructure.campaign_repository,
                infrastructure.job_repository,
            ),
            mutation_policy,
        ),
        create_processing_job_for_audio_track=CreateProcessingJobForAudioTrack(
            infrastructure.campaign_repository,
            infrastructure.audio_track_repository,
            infrastructure.job_repository,
            infrastructure.clock,
            infrastructure.id_generator,
        ),
        submit_recording_for_processing=GuardedCampaignMutation(
            SubmitRecordingForProcessing(
                infrastructure.campaign_repository,
                infrastructure.audio_track_repository,
                infrastructure.job_repository,
                infrastructure.metadata_reader,
                infrastructure.source_metadata_reader,
                infrastructure.artifact_storage,
                infrastructure.clock,
                infrastructure.id_generator,
                audio_normalizer=infrastructure.audio_normalizer,
            ),
            mutation_policy,
        ),
        queue_processing_job=queue_processing_job,
        run_processing_job=queue_processing_job,
        restart_failed_processing_job=restart_processing_job,
        clear_failed_jobs_for_campaign=ClearFailedJobsForCampaign(
            infrastructure.campaign_repository,
            infrastructure.job_repository,
            infrastructure.job_cleaner,
        ),
        delete_processing_job=DeleteProcessingJob(
            infrastructure.job_repository,
            infrastructure.job_cleaner,
        ),
        cancel_processing_job=CancelProcessingJob(
            infrastructure.job_repository,
            infrastructure.clock,
            job_manager,
            infrastructure.speaker_review_submission_repository,
        ),
        list_jobs_for_campaign=ListJobsForCampaign(
            infrastructure.campaign_repository,
            infrastructure.job_repository,
        ),
        get_job_status=GetJobStatus(infrastructure.job_repository),
        review_speaker_mappings=ReviewSpeakerMappings(
            infrastructure.campaign_repository,
            infrastructure.transcript_repository,
            infrastructure.job_repository,
            infrastructure.speaker_review_submission_repository,
            job_manager,
            infrastructure.clock,
        ),
        generate_recap=GenerateRecap(
            infrastructure.job_repository,
            infrastructure.transcript_repository,
            infrastructure.recap_repository,
            infrastructure.tokenizer,
            infrastructure.recap_guidances,
            infrastructure.recap_generator,
            infrastructure.clock,
            infrastructure.id_generator,
            progress_tracker_factory=progress_tracker_factory,
        ),
        get_recap_guidances=GetRecapGuidances(
            infrastructure.campaign_repository,
            infrastructure.recap_guidances,
        ),
        update_recap_guidances=UpdateRecapGuidances(
            infrastructure.campaign_repository,
            infrastructure.recap_guidances,
            mutation_policy,
        ),
        export_transcript_markdown=ExportTranscriptMarkdown(
            infrastructure.transcript_repository,
            infrastructure.artifact_storage,
        ),
        export_recap_markdown=ExportRecapMarkdown(
            infrastructure.recap_repository,
            infrastructure.artifact_storage,
        ),
        preview_transcript_markdown=PreviewTranscriptMarkdown(
            infrastructure.transcript_repository,
        ),
        preview_recap_markdown=PreviewRecapMarkdown(infrastructure.recap_repository),
        inspect_audio_metadata=InspectAudioMetadata(infrastructure.metadata_reader),
        inspect_local_audio_file=InspectLocalAudioFile(
            infrastructure.source_metadata_reader,
        ),
        sync_campaign_folder=GuardedCampaignMutation(
            SyncCampaignFolder(
                infrastructure.campaign_repository,
                infrastructure.job_repository,
                infrastructure.folder_scanner,
                infrastructure.metadata_reader,
                infrastructure.id_generator,
                audio_normalizer=infrastructure.audio_normalizer,
                artifact_storage=infrastructure.artifact_storage,
            ),
            mutation_policy,
        ),
        restart_processing_job=restart_processing_job,
    )


__all__ = ["wire_stage1_use_cases"]

