"""Ports used by the application layer."""

from .auth import AuthProvider

from .events import (
    DashboardEventHub,
    DashboardEventListener,
    DashboardEventPublisher,
    DashboardEventStream,
    ProgressEventHub,
    ProgressEventListener,
    ProgressEventPublisher,
    ProgressEventSnapshotStore,
    ProgressEventStream,
    ProgressTracker,
    ProgressTrackerFactory,
    Unsubscribe,
)
from .processing import (
    AudioMetadataReader,
    AudioProcessor,
    AudioRecordingNormalizer,
    CampaignMutationGuard,
    FailedJobCleaner,
    JobCleaner,
    JobManager,
    SourceAudioMetadataReader,
    SpeakerIdentifier,
    Tokenizer,
    Transcriber,
    TransientAudioCleaner,
)
from .recaps import RecapGenerator, RecapGeneratorFactory, RecapGuidances
from .repositories import (
    AudioTrackRepository,
    CampaignRepository,
    JobRepository,
    ParticipantRepository,
    RecapRepository,
    SpeakerMappingRepository,
    SpeakerReviewSubmissionRepository,
    TranscriptRepository,
    VoiceSampleRepository,
    WorkspaceRepository,
)
from .runtime import Clock, IdGenerator
from .settings import UserPreferencesRepository, WorkspaceSettingsRepository
from .storage import (
    ArtifactStorage,
    CampaignArtifactStorage,
    CampaignFolderScanner,
    PreparedAudioManifestStore,
)

__all__ = [
    "ArtifactStorage",
    "AuthProvider",
    "AudioMetadataReader",
    "AudioProcessor",
    "AudioRecordingNormalizer",
    "AudioTrackRepository",
    "CampaignArtifactStorage",
    "CampaignFolderScanner",
    "CampaignMutationGuard",
    "CampaignRepository",
    "Clock",
    "DashboardEventHub",
    "DashboardEventListener",
    "DashboardEventPublisher",
    "DashboardEventStream",
    "FailedJobCleaner",
    "IdGenerator",
    "JobCleaner",
    "JobManager",
    "JobRepository",
    "ParticipantRepository",
    "PreparedAudioManifestStore",
    "ProgressEventHub",
    "ProgressEventListener",
    "ProgressEventPublisher",
    "ProgressEventSnapshotStore",
    "ProgressEventStream",
    "ProgressTracker",
    "ProgressTrackerFactory",
    "RecapGenerator",
    "RecapGeneratorFactory",
    "RecapGuidances",
    "RecapRepository",
    "SourceAudioMetadataReader",
    "SpeakerIdentifier",
    "SpeakerMappingRepository",
    "SpeakerReviewSubmissionRepository",
    "Tokenizer",
    "Transcriber",
    "TransientAudioCleaner",
    "TranscriptRepository",
    "Unsubscribe",
    "UserPreferencesRepository",
    "VoiceSampleRepository",
    "WorkspaceRepository",
    "WorkspaceSettingsRepository",
]
