"""Clock and identifier generation ports."""

from datetime import datetime
from typing import Protocol


class Clock(Protocol):
    def now(self) -> datetime: ...


class IdGenerator(Protocol):
    def campaign_id(self) -> str: ...

    def participant_id(self) -> str: ...

    def voice_sample_id(self) -> str: ...

    def audio_track_id(self) -> str: ...

    def processing_job_id(self) -> str: ...

    def transcript_id(self) -> str: ...

    def recap_id(self) -> str: ...

